### ISSUE TITLE
配置v2ray后443端口不能使用

### ISSUE THREAD

**Issue by baihangyu** [yeahwu/v2ray-wss#12]
配置以后ss和8080能正常使用，可是443端口无法使用，ssh到主机使用netstat命令查看端口状态，显示没有进程在监听443端口，应该如何启用443端口和tls加密功能？
![mmexport1667805363148](https://user-images.githubusercontent.com/15261516/200247597-f1763e00-7e2a-4b4a-8ee7-95aecf7aa1ff.jpg)

**Comment by yeahwu** [comment]
可能是证书没有申请成功，`nginx -t` 看看
或者重新再跑一下脚本

**Comment by baihangyu** [comment]
已解决，重新跑了一遍脚本还是问题依旧，重新申请了一下证书，执行` certbot certonly --renew-by-default --register-unsafely-without-email --standalone -d 域名`，在重启一下nginx就行了。

翻回前面的安装过程，看到申请证书的时候报了一个错误，见下图
![WX20221111-002626](https://user-images.githubusercontent.com/15261516/201151418-deba3187-58c7-4434-a14a-d8f987c6ba18.png)
楼主看下是不是脚本这个位置需要修改一下

**Comment by yeahwu** [comment]
@baihangyu 谢谢反馈，问一下你用的是什么系统？

**Comment by baihangyu** [comment]
> 

Ubuntu 22.04 64 Bit

**Comment by baihangyu** [comment]
> @baihangyu 谢谢反馈，问一下你用的是什么系统？

系统是：Ubuntu 22.04 64 Bit

**Comment by yeahwu** [comment]
好的，已经修复了。
