### ISSUE TITLE
建议加个提醒，一定要通过防火墙打开相应的端口

### ISSUE THREAD

**Issue by wakaka123wakaka** [yeahwu/v2ray-wss#21]
建议加个提醒，一定要通过防火墙打开相应的端口，我是debian 11的折腾了一晚上，死活nmap检测端口一会存活，一会关闭，一会可以访问，一会就不行了，然后换了其他的脚本，都是一个样子，最后把防火墙关了就好了

**Comment by yeahwu** [comment]
好建议，稍后加提醒。
