### ISSUE TITLE
建议增加自定义端口

### ISSUE THREAD

**Issue by Vict0r-Chen** [yeahwu/v2ray-wss#22]
因为此前有部分端口（443、80等）被封了，建议可以随机生成端口或让用户手动填写~

**Comment by yeahwu** [comment]
已经添加了自定义端口

**Comment by JssDream** [comment]
@yeahwu 怎么进行自定义端口？刚刚使用脚本安装没看到需要输入端口？直接随机生成端口了？

**Comment by yeahwu** [comment]
> @yeahwu 怎么进行自定义端口？刚刚使用脚本安装没看到需要输入端口？直接随机生成端口了？

wss代理和reality支持自定义端口，15秒内可自定义输入，过了15秒默认443端口。ss暂时还不支持自定义端口。
