### ISSUE TITLE
安装完以后 怎么查看配置的信息啊。。。忘记了 不知道怎么去查看

### ISSUE THREAD

**Issue by qq1254870524** [yeahwu/v2ray-wss#25]
安装完以后 怎么查看配置的信息啊。。。忘记了 不知道怎么去查看。有没有通过链接添加，怎么弄每天换个IP呢/。像拨号一样 可以换IP

**Comment by yeahwu** [comment]
WSS客户端配置信息保存在： cat /usr/local/etc/v2ray/client.json

Shadowsocks客户端配置信息： cat /etc/shadowsocks-libev/config.json

Reality客户端配置信息保存在： cat /usr/local/etc/xray/reclient.json
