### ISSUE TITLE
安装过程中报错

### ISSUE THREAD

**Issue by Simonaorg** [yeahwu/v2ray-wss#28]
安装过程中报错，代码跳太快，没法复制过来，试了azure和aws的都在安装过程中报错用不了

**Comment by Simonaorg** [comment]
ws+tls那个协议

**Comment by 0utsiderZhong** [comment]
**至少要贴个具体报错才能帮你**

你可以看看nginx进程的状态 看看申请证书的80端口是否被占用  解析是否正确等等，太多原因了

**Comment by crazypeace** [comment]
> 安装过程中报错，代码跳太快，没法复制过来，试了azure和aws的都在安装过程中报错用不了

xshell 可以自动记录日志。
https://zelikk.blogspot.com/2022/03/xshell-auto-log.html
