### ISSUE TITLE
ss安装后报错

### ISSUE THREAD

**Issue by wojiaopanhaoran** [yeahwu/v2ray-wss#5]
systemctl status：
shadowsocks.service - Shadowsocks Server
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 二 2022-04-12 23:09:37 CST; 2s ago
  Process: 8463 ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json (code=exited, status=203/EXEC)
 Main PID: 8463 (code=exited, status=203/EXEC)

4月 12 23:09:37 C20220412219383 systemd[1]: Started Shadowsocks Server.
4月 12 23:09:37 C20220412219383 systemd[1]: shadowsocks.service: main process exited, code=exited, status=203/EXEC
4月 12 23:09:37 C20220412219383 systemd[1]: Unit shadowsocks.service entered failed state.
4月 12 23:09:37 C20220412219383 systemd[1]: shadowsocks.service failed.

journalctl：
4月 12 23:44:13 C20220412219383 systemd[4861]: Failed at step EXEC spawning /usr/bin/ss-server: Permission denied
-- Subject: Process /usr/bin/ss-server could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /usr/bin/ss-server could not be executed and failed.
-- 
-- The error number returned by this process is 13.
4月 12 23:44:13 C20220412219383 systemd[1]: shadowsocks.service: main process exited, code=exited, status=203/EXEC
4月 12 23:44:13 C20220412219383 systemd[1]: Unit shadowsocks.service entered failed state.
4月 12 23:44:13 C20220412219383 systemd[1]: shadowsocks.service failed.
4月 12 23:44:13 C20220412219383 polkitd[1530]: Unregistered Authentication Agent for unix-process:4855:249422 (system bus n

centos 7.6
搜了一下可能是启动.sh第一行少#!/bin/sh，但是没找到启动.sh在哪，请大佬教一下

**Comment by yeahwu** [comment]
可能是系统的原因，建议更换Ubuntu或者Debian.

如果不能更换系统的话，至少 `yum update && yum upgrade` 更新一下系统，再次运行脚本试试。

**Comment by wojiaopanhaoran** [comment]
> 可能是系统的原因，建议更换Ubuntu或者Debian.
> 
> 如果不能更换系统的话，至少 `yum update && yum upgrade` 更新一下系统，再次运行脚本试试。

模板里的系统太过于精简了，update后不报错了，谢谢大佬
